# Generated by Django 5.2.4 on 2025-07-05 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Acessório')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Acessório',
                'verbose_name_plural': 'Acessórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FaixaTecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Faixa')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mínimo')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Máximo')),
            ],
            options={
                'verbose_name': 'Faixa de Tecido',
                'verbose_name_plural': 'Faixas de Tecido',
                'ordering': ['valor_minimo'],
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Linha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Item',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ref_produto', models.CharField(max_length=50, unique=True, verbose_name='Referência do Produto')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tem_cor_tecido', models.BooleanField(default=False, verbose_name='Tem Cor Tecido')),
                ('tem_difer_desenho_lado_dir_esq', models.BooleanField(default=False, verbose_name='Diferencia Desenho Lado Direito/Esquerdo')),
                ('tem_difer_desenho_tamanho', models.BooleanField(default=False, verbose_name='Diferencia Desenho por Tamanho')),
                ('id_linha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.linha', verbose_name='Linha')),
                ('id_tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.tipoitem', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['ref_produto'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo')),
                ('largura_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largura Total (cm)')),
                ('largura_assento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Largura do Assento (cm)')),
                ('tecido_metros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tecido (metros)')),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Volume (m³)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='produtos.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['item', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecosBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_inic_vigencia', models.DateField(verbose_name='Data Início Vigência')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Base')),
                ('id_faixa_tecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.faixatecido', verbose_name='Faixa de Tecido')),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Preço Base',
                'verbose_name_plural': 'Preços Base',
                'ordering': ['-data_inic_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='AcessoriosItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('id_acessorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.acessorio', verbose_name='Acessório')),
                ('id_linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.linha', verbose_name='Linha')),
            ],
            options={
                'verbose_name': 'Acessório do Item',
                'verbose_name_plural': 'Acessórios dos Itens',
                'unique_together': {('id_acessorio', 'id_linha')},
            },
        ),
        migrations.CreateModel(
            name='TamanhosModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tamanho', models.CharField(max_length=50, verbose_name='Tamanho')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Tamanho do Módulo',
                'verbose_name_plural': 'Tamanhos dos Módulos',
                'unique_together': {('id_modulo', 'tamanho')},
            },
        ),
    ]
