# Generated by Django 5.2.4 on 2025-07-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso (kg)'),
        ),
        migrations.CreateModel(
            name='TamanhosModulosDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome_tamanho', models.CharField(max_length=50, verbose_name='Nome do Tamanho')),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura (cm)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura (cm)')),
                ('profundidade_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidade (cm)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Tamanho')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanhos_detalhados', to='produtos.modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Tamanho Detalhado do Módulo',
                'verbose_name_plural': 'Tamanhos Detalhados dos Módulos',
                'unique_together': {('id_modulo', 'nome_tamanho')},
            },
        ),
    ]
