# Generated by Django 5.2.4 on 2025-07-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_modulo_peso_kg_tamanhosmodulosdetalhado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='largura_assento',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='largura_total',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='tecido_metros',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='volume_m3',
        ),
        migrations.RemoveField(
            model_name='tamanhosmodulosdetalhado',
            name='largura_cm',
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='largura_assento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura do Assento (cm)'),
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='largura_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura Total (cm)'),
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='tecido_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tecido (metros)'),
        ),
        migrations.AddField(
            model_name='tamanhosmodulosdetalhado',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volume (m³)'),
        ),
    ]
