# Generated by Django 5.2.4 on 2025-07-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_modulo_largura_assento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/itens/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='item',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/itens/', verbose_name='Imagem Secundária'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/modulos/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/modulos/', verbose_name='Imagem Secundária'),
        ),
    ]
