# Generated by Django 4.2.7 on 2025-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_item_imagem_principal_item_imagem_secundaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id_linha',
        ),
        migrations.AddField(
            model_name='modulo',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='braco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Braço (cm)'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profundidade (cm)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/itens/', verbose_name='Imagem Secundária (Opcional)'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/modulos/', verbose_name='Imagem Secundária (Opcional)'),
        ),
    ]
