# Generated by Django 4.2.7 on 2025-07-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_remove_item_id_linha_modulo_altura_modulo_braco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imagem_secundaria',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='imagem_secundaria',
        ),
    ]
