# Generated by Django 4.2.7 on 2025-07-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_remove_item_imagem_secundaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcessoriosItens',
        ),
    ]
