# Generated by Django 4.2.7 on 2025-07-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_remove_acessorios_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamanhosmodulosdetalhado',
            name='altura_cm',
        ),
        migrations.RemoveField(
            model_name='tamanhosmodulosdetalhado',
            name='profundidade_cm',
        ),
    ]
