# Generated by Django 4.2.7 on 2025-07-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_remove_altura_profundidade_from_tamanhos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tamanhosmodulosdetalhado',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tamanhosmodulosdetalhado',
            name='nome_tamanho',
        ),
    ]
