# Generated by Django 4.2.7 on 2025-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_remove_nome_tamanho_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'ordering': ['ref_acessorio'], 'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AddField(
            model_name='acessorio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/acessorios/', verbose_name='Imagem Principal'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/acessorios/', verbose_name='Imagem Adicional'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='produtos_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Produtos aos quais este acessório pode ser vinculado', to='produtos.item', verbose_name='Produtos Vinculados'),
        ),
        migrations.AddField(
            model_name='acessorio',
            name='ref_acessorio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Referência do Acessório'),
        ),
    ]
