# Generated by Django 4.2.7 on 2025-07-06 05:53

from django.db import migrations


def populate_ref_acessorio(apps, schema_editor):
    """Populate ref_acessorio field for existing accessories"""
    Acessorio = apps.get_model('produtos', 'Acessorio')
    for i, acessorio in enumerate(Acessorio.objects.all(), 1):
        if not acessorio.ref_acessorio:
            acessorio.ref_acessorio = f"ACESS{i:03d}"
            acessorio.save()


def reverse_populate_ref_acessorio(apps, schema_editor):
    """Reverse operation - clear ref_acessorio field"""
    Acessorio = apps.get_model('produtos', 'Acessorio')
    Acessorio.objects.all().update(ref_acessorio=None)


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_alter_acessorio_options_acessorio_ativo_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_ref_acessorio, reverse_populate_ref_acessorio),
    ]
