# Generated by Django 4.2.7 on 2025-07-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_auto_20250706_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descricao_acessorio',
            field=models.TextField(blank=True, help_text='Apenas para produtos do tipo acessório', null=True, verbose_name='Descrição do Acessório'),
        ),
        migrations.AddField(
            model_name='item',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/itens/', verbose_name='Imagem Secundária'),
        ),
        migrations.AddField(
            model_name='item',
            name='preco_acessorio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Apenas para produtos do tipo acessório', max_digits=10, null=True, verbose_name='Preço do Acessório (R$)'),
        ),
        migrations.AddField(
            model_name='item',
            name='produtos_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Para acessórios: produtos aos quais este acessório pode ser vinculado', to='produtos.item', verbose_name='Produtos Vinculados'),
        ),
        migrations.AlterField(
            model_name='acessorio',
            name='ref_acessorio',
            field=models.CharField(max_length=50, unique=True, verbose_name='Referência do Acessório'),
        ),
    ]
