# Generated by Django 4.2.7 on 2025-07-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_item_descricao_acessorio_item_imagem_secundaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='imagem_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/modulos/', verbose_name='Imagem Secundária'),
        ),
    ]
