# Generated by Django 4.2.7 on 2025-07-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0015_banqueta'),
    ]

    operations = [
    ]
