# Generated by Django 4.2.7 on 2025-07-07 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0016_auto_20250706_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ref_cadeira', models.CharField(help_text='Ex: CD13, CD249, etc.', max_length=50, unique=True, verbose_name='Referência da Cadeira')),
                ('nome', models.CharField(help_text='Ex: OFFICE, CONFORT, etc.', max_length=100, verbose_name='Nome da Cadeira')),
                ('largura', models.DecimalField(decimal_places=2, help_text='Largura em centímetros', max_digits=10, verbose_name='Largura (cm)')),
                ('profundidade', models.DecimalField(decimal_places=2, help_text='Profundidade em centímetros', max_digits=10, verbose_name='Profundidade (cm)')),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em centímetros', max_digits=10, verbose_name='Altura (cm)')),
                ('tecido_metros', models.DecimalField(decimal_places=2, help_text='Quantidade de tecido necessária em metros', max_digits=10, verbose_name='Tecido (m)')),
                ('volume_m3', models.DecimalField(decimal_places=3, help_text='Volume para cálculo de frete em metros cúbicos', max_digits=10, verbose_name='Volume (m³)')),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso para cálculo de frete em quilogramas', max_digits=10, verbose_name='Peso (kg)')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço em reais', max_digits=10, verbose_name='Preço (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/cadeiras/', verbose_name='Imagem Principal')),
                ('imagem_secundaria', models.ImageField(blank=True, null=True, upload_to='produtos/cadeiras/', verbose_name='Imagem Secundária')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Cadeira',
                'verbose_name_plural': 'Cadeiras',
                'ordering': ['ref_cadeira'],
            },
        ),
    ]
