# Generated by Django 4.2.7 on 2025-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(help_text='Ex: EVA, EVA BR, FIT, etc.', max_length=100, verbose_name='Nome da Cadeira'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='ref_cadeira',
            field=models.CharField(help_text='Ex: CD001, CD24, CD267, etc.', max_length=50, unique=True, verbose_name='Referência da Cadeira'),
        ),
    ]
