# Generated by Django 4.2.7 on 2025-07-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0019_pufe_poltrona_almofada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poltrona',
            name='nome',
            field=models.CharField(help_text='Ex: ARIA, ARISTOCRATA, CERNE, etc.', max_length=100, verbose_name='Nome da Poltrona'),
        ),
        migrations.AlterField(
            model_name='poltrona',
            name='ref_poltrona',
            field=models.CharField(help_text='Ex: PL243, PL246, PL105, etc.', max_length=50, unique=True, verbose_name='Referência da Poltrona'),
        ),
    ]
