# Generated by Django 4.2.7 on 2025-07-07 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0020_alter_poltrona_nome_alter_poltrona_ref_poltrona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['ref_produto'], 'verbose_name': 'Item (Deprecated)', 'verbose_name_plural': 'Itens (Deprecated)'},
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ref_produto', models.CharField(max_length=50, unique=True, verbose_name='Referência do Produto')),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem Principal')),
                ('imagem_secundaria', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem Secundária')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('id_tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.tipoitem', verbose_name='Tipo de Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos_produto',
                'ordering': ['ref_produto'],
            },
        ),
        migrations.AlterField(
            model_name='acessorio',
            name='produtos_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Produtos aos quais este acessório pode ser vinculado', to='produtos.produto', verbose_name='Produtos Vinculados'),
        ),
    ]
