# Generated by Django 4.2.7 on 2025-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0022_migrar_modulos_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tem_cor_tecido',
            field=models.BooleanField(default=False, help_text='Apenas para sofás e produtos similares', verbose_name='Tem Cor Tecido'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tem_difer_desenho_lado_dir_esq',
            field=models.BooleanField(default=False, help_text='Apenas para sofás e produtos similares', verbose_name='Diferencia Desenho Lado Direito/Esquerdo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tem_difer_desenho_tamanho',
            field=models.BooleanField(default=False, help_text='Apenas para sofás e produtos similares', verbose_name='Diferencia Desenho por Tamanho'),
        ),
    ]
