# Generated by Django 4.2.7 on 2025-07-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0023_produto_tem_cor_tecido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['produto', 'nome'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='item',
            new_name='produto',
        ),
    ]
