# Generated by Django 4.2.7 on 2025-07-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0024_alter_modulo_options_rename_item_modulo_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeira',
            name='tem_cor_tecido',
            field=models.BooleanField(default=False, help_text='Indica se a cadeira utiliza diferentes cores de tecido', verbose_name='Tem Cor Tecido'),
        ),
        migrations.AddField(
            model_name='poltrona',
            name='tem_cor_tecido',
            field=models.BooleanField(default=False, help_text='Indica se a poltrona utiliza diferentes cores de tecido', verbose_name='Tem Cor Tecido'),
        ),
    ]
