# Generated by Django 4.2.7 on 2025-08-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0025_cadeira_tem_cor_tecido_poltrona_tem_cor_tecido'),
    ]

    operations = [
        migrations.CreateModel(
            name='SofaAcessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade do acessório para este sofá', verbose_name='Quantidade')),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas sobre este acessório para este sofá', max_length=1000, null=True, verbose_name='Observações')),
                ('acessorio', models.ForeignKey(help_text='Acessório vinculado ao sofá', on_delete=django.db.models.deletion.CASCADE, to='produtos.acessorio', verbose_name='Acessório')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sofa', models.ForeignKey(help_text='Sofá ao qual o acessório está vinculado', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Sofá')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Sofá - Acessório',
                'verbose_name_plural': 'Sofás - Acessórios',
                'ordering': ['sofa__ref_produto', 'acessorio__ref_acessorio'],
                'unique_together': {('sofa', 'acessorio')},
            },
        ),
    ]
