# Generated by Django 4.2.7 on 2025-08-31 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0026_add_sofa_acessorio_through_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tamanho', models.CharField(blank=True, help_text='Ex: 40x40, P, M, G, 80cm, Baixo/Alto', max_length=100, null=True, verbose_name='Tamanho')),
                ('cor', models.CharField(blank=True, help_text='Ex: Azul, Listrado, Floral', max_length=100, null=True, verbose_name='Cor/Estampa')),
                ('material', models.CharField(blank=True, help_text='Ex: Madeira, Metal, Tecido, Couro', max_length=100, null=True, verbose_name='Material')),
                ('atributos_especificos', models.JSONField(blank=True, default=dict, help_text='Campos específicos por tipo de produto', verbose_name='Atributos Específicos')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço (R$)')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'ordering': ['produto', 'tamanho', 'cor'],
                'unique_together': {('produto', 'tamanho', 'cor', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoAcessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantidade sugerida do acessório para este produto', verbose_name='Quantidade Sugerida')),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas sobre este acessório para este produto', max_length=1000, null=True, verbose_name='Observações')),
                ('acessorio', models.ForeignKey(help_text='Acessório compatível com o produto', on_delete=django.db.models.deletion.CASCADE, to='produtos.acessorio', verbose_name='Acessório')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('produto', models.ForeignKey(help_text='Produto ao qual o acessório está vinculado', on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Produto - Acessório',
                'verbose_name_plural': 'Produtos - Acessórios',
                'ordering': ['produto__ref_produto', 'acessorio__ref_acessorio'],
                'unique_together': {('produto', 'acessorio')},
            },
        ),
    ]
