# Generated by Django 4.2.7 on 2025-07-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_created_by_customuser_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo_permissao',
            field=models.CharField(choices=[('master', 'Master'), ('admin', 'Admin'), ('vendedor', 'Vendedor'), ('operador_produtos', 'Operador de Produtos')], default='operador_produtos', max_length=20, verbose_name='Tipo de Permissão'),
        ),
    ]
