# Generated by Django 4.2.7 on 2025-07-05 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(help_text='Razão social ou nome fantasia da empresa', max_length=200, verbose_name='Nome da Empresa')),
                ('representante', models.CharField(help_text='Nome do representante da empresa', max_length=150, verbose_name='Representante')),
                ('cnpj', models.CharField(help_text='CNPJ no formato 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('logradouro', models.CharField(help_text='Rua, avenida, praça, etc.', max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Apartamento, sala, andar, etc.', max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(help_text='UF do estado (ex: SP, RJ, MG)', max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(help_text='CEP no formato 00000-000', max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('telefone', models.CharField(help_text='Telefone com DDD', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(help_text='E-mail principal da empresa', max_length=254, verbose_name='E-mail')),
                ('banco', models.CharField(blank=True, help_text='Nome do banco', max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, help_text='Número da agência', max_length=20, null=True, verbose_name='Agência')),
                ('conta_corrente', models.CharField(blank=True, help_text='Número da conta corrente', max_length=30, null=True, verbose_name='Conta Corrente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_empresa'],
            },
        ),
    ]
