# Generated by Django 4.2.7 on 2025-07-08 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0025_cadeira_tem_cor_tecido_poltrona_tem_cor_tecido'),
        ('clientes', '0002_cliente_created_by_cliente_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Faixa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('multiplicador', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador aplicado ao preço base (1.00 = 100%)', max_digits=5, verbose_name='Multiplicador')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'verbose_name_plural': 'Faixas de Preço',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('prazo_dias', models.IntegerField(default=0, help_text='Prazo padrão em dias para esta forma de pagamento', verbose_name='Prazo em dias')),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto máximo permitido para esta forma de pagamento', max_digits=5, verbose_name='Desconto Máximo (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('numero', models.CharField(help_text='Número único do orçamento', max_length=20, unique=True, verbose_name='Número do Orçamento')),
                ('desconto_valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do desconto em reais', max_digits=10, verbose_name='Desconto (R$)')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de desconto', max_digits=5, verbose_name='Desconto (%)')),
                ('acrescimo_valor', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do acréscimo em reais', max_digits=10, verbose_name='Acréscimo (R$)')),
                ('acrescimo_percentual', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de acréscimo', max_digits=5, verbose_name='Acréscimo (%)')),
                ('data_entrega', models.DateField(help_text='Data prevista para entrega', verbose_name='Data de Entrega')),
                ('data_validade', models.DateField(help_text='Data de validade do orçamento', verbose_name='Data de Validade')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais do orçamento', null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('faixa_preco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamentos.faixapreco', verbose_name='Faixa de Preço')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orcamentos.formapagamento', verbose_name='Forma de Pagamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('vendedor', models.ForeignKey(limit_choices_to={'tipo_permissao__in': ['vendedor', 'admin', 'master']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, help_text='Preço unitário já com faixa de preço aplicada', max_digits=10, verbose_name='Preço Unitário')),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas deste item', null=True, verbose_name='Observações')),
                ('dados_produto', models.JSONField(blank=True, default=dict, help_text='Dados específicos do produto (cor, tamanho, etc.)', verbose_name='Dados do Produto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orcamentos.orcamento', verbose_name='Orçamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto', verbose_name='Produto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Item do Orçamento',
                'verbose_name_plural': 'Itens do Orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('modulo_id', models.PositiveIntegerField(help_text='ID do módulo original do produto', verbose_name='ID do Módulo')),
                ('nome_modulo', models.CharField(max_length=200, verbose_name='Nome do Módulo')),
                ('tamanho_selecionado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamanho Selecionado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('item_orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='orcamentos.orcamentoitem', verbose_name='Item do Orçamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Módulo do Orçamento',
                'verbose_name_plural': 'Módulos do Orçamento',
                'ordering': ['id'],
            },
        ),
    ]
