# Generated by Django 4.2.7 on 2025-07-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
    ]
