# Generated by Django 4.2.7 on 2025-07-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_auto_20250708_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='acrescimo_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentual de acréscimo', max_digits=5, null=True, verbose_name='Acréscimo (%)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='acrescimo_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Valor do acréscimo em reais', max_digits=10, null=True, verbose_name='Acréscimo (R$)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Percentual de desconto', max_digits=5, null=True, verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Valor do desconto em reais', max_digits=10, null=True, verbose_name='Desconto (R$)'),
        ),
    ]
