# Generated by Django 4.2.7 on 2025-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0003_alter_orcamento_acrescimo_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentomodulo',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações específicas deste módulo', max_length=1000, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='orcamentomodulo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='orcamentomodulo',
            name='tamanho_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID do tamanho detalhado selecionado', null=True, verbose_name='ID do Tamanho'),
        ),
    ]
